=begin
#Bckbn Pay API

#API for Bckbn Pay services

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BckbnPay::PaymentIntentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentIntentsApi' do
  before do
    # run before each test
    @api_instance = BckbnPay::PaymentIntentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentIntentsApi' do
    it 'should create an instance of PaymentIntentsApi' do
      expect(@api_instance).to be_instance_of(BckbnPay::PaymentIntentsApi)
    end
  end

  # unit tests for confirm_payment_intent
  # Confirm a payment intent
  # @param x_api_version 
  # @param id The ID of the payment intent to confirm
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentResponse]
  describe 'confirm_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_payment_intent
  # Create a new payment intent
  # @param x_api_version 
  # @param payment_intent_attributes 
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentResponse]
  describe 'create_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_payment_intent
  # Retrieve a payment intent by ID
  # @param x_api_version 
  # @param id The ID of the payment intent to retrieve
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentResponse]
  describe 'get_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_payment_intents
  # List payment intents
  # @param x_api_version 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of results to retrieve.
  # @option opts [Integer] :per_page Number of results per page.
  # @option opts [String] :sub_merchant_id Filter results by sub_merchant ID.
  # @return [ListPaymentIntentsResponse]
  describe 'list_payment_intents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_payment_intent
  # Update a payment intent
  # @param x_api_version 
  # @param id The ID of the payment intent to update
  # @param update_payment_intent_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentResponse]
  describe 'update_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
